apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nodeapp-com-app-db-password
  namespace: dev-tti
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: deepagent-aws
    kind: ClusterSecretStore
  target:
    name: app-env
    creationPolicy: Merge
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: this-dev-8-dev/dev-tti/DB_PASSWORD
